/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProyectosIdRouteImport } from './routes/proyectos.$id'
import { Route as AuthRestablecerRouteImport } from './routes/auth.restablecer'
import { Route as AuthRecuperarRouteImport } from './routes/auth.recuperar'
import { Route as AuthenticatedVerificacionRouteImport } from './routes/_authenticated/verificacion'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMensajesRouteImport } from './routes/_authenticated/mensajes'
import { Route as AuthenticatedDescubrirRouteImport } from './routes/_authenticated/descubrir'
import { Route as AuthenticatedConexionesRouteImport } from './routes/_authenticated/conexiones'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProyectosIndexRouteImport } from './routes/_authenticated/proyectos.index'
import { Route as AuthenticatedInversorIndexRouteImport } from './routes/_authenticated/inversor.index'
import { Route as AuthenticatedEmpresaIndexRouteImport } from './routes/_authenticated/empresa.index'
import { Route as AuthenticatedInversorSolicitudesRouteImport } from './routes/_authenticated/inversor.solicitudes'
import { Route as AuthenticatedInversorPerfilRouteImport } from './routes/_authenticated/inversor.perfil'
import { Route as AuthenticatedInversorFavoritosRouteImport } from './routes/_authenticated/inversor.favoritos'
import { Route as AuthenticatedEmpresaSolicitudesRouteImport } from './routes/_authenticated/empresa.solicitudes'
import { Route as AuthenticatedEmpresaPerfilRouteImport } from './routes/_authenticated/empresa.perfil'
import { Route as AuthenticatedEmpresaNuevoRouteImport } from './routes/_authenticated/empresa.nuevo'
import { Route as AuthenticatedEmpresaIdInversoresRouteImport } from './routes/_authenticated/empresa.$id.inversores'
import { Route as AuthenticatedEmpresaIdEditarRouteImport } from './routes/_authenticated/empresa.$id.editar'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIdRoute = ProyectosIdRouteImport.update({
  id: '/proyectos/$id',
  path: '/proyectos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRestablecerRoute = AuthRestablecerRouteImport.update({
  id: '/restablecer',
  path: '/restablecer',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecuperarRoute = AuthRecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedVerificacionRoute =
  AuthenticatedVerificacionRouteImport.update({
    id: '/verificacion',
    path: '/verificacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMensajesRoute = AuthenticatedMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDescubrirRoute = AuthenticatedDescubrirRouteImport.update({
  id: '/descubrir',
  path: '/descubrir',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConexionesRoute = AuthenticatedConexionesRouteImport.update({
  id: '/conexiones',
  path: '/conexiones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProyectosIndexRoute =
  AuthenticatedProyectosIndexRouteImport.update({
    id: '/proyectos/',
    path: '/proyectos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInversorIndexRoute =
  AuthenticatedInversorIndexRouteImport.update({
    id: '/inversor/',
    path: '/inversor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresaIndexRoute =
  AuthenticatedEmpresaIndexRouteImport.update({
    id: '/empresa/',
    path: '/empresa/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInversorSolicitudesRoute =
  AuthenticatedInversorSolicitudesRouteImport.update({
    id: '/inversor/solicitudes',
    path: '/inversor/solicitudes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInversorPerfilRoute =
  AuthenticatedInversorPerfilRouteImport.update({
    id: '/inversor/perfil',
    path: '/inversor/perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInversorFavoritosRoute =
  AuthenticatedInversorFavoritosRouteImport.update({
    id: '/inversor/favoritos',
    path: '/inversor/favoritos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresaSolicitudesRoute =
  AuthenticatedEmpresaSolicitudesRouteImport.update({
    id: '/empresa/solicitudes',
    path: '/empresa/solicitudes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresaPerfilRoute =
  AuthenticatedEmpresaPerfilRouteImport.update({
    id: '/empresa/perfil',
    path: '/empresa/perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresaNuevoRoute =
  AuthenticatedEmpresaNuevoRouteImport.update({
    id: '/empresa/nuevo',
    path: '/empresa/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresaIdInversoresRoute =
  AuthenticatedEmpresaIdInversoresRouteImport.update({
    id: '/empresa/$id/inversores',
    path: '/empresa/$id/inversores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresaIdEditarRoute =
  AuthenticatedEmpresaIdEditarRouteImport.update({
    id: '/empresa/$id/editar',
    path: '/empresa/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/ayuda': typeof AyudaRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/legal': typeof LegalRoute
  '/planes': typeof PlanesRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/app': typeof AuthenticatedAppRoute
  '/conexiones': typeof AuthenticatedConexionesRoute
  '/descubrir': typeof AuthenticatedDescubrirRoute
  '/mensajes': typeof AuthenticatedMensajesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/verificacion': typeof AuthenticatedVerificacionRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/restablecer': typeof AuthRestablecerRoute
  '/proyectos/$id': typeof ProyectosIdRoute
  '/empresa/nuevo': typeof AuthenticatedEmpresaNuevoRoute
  '/empresa/perfil': typeof AuthenticatedEmpresaPerfilRoute
  '/empresa/solicitudes': typeof AuthenticatedEmpresaSolicitudesRoute
  '/inversor/favoritos': typeof AuthenticatedInversorFavoritosRoute
  '/inversor/perfil': typeof AuthenticatedInversorPerfilRoute
  '/inversor/solicitudes': typeof AuthenticatedInversorSolicitudesRoute
  '/empresa/': typeof AuthenticatedEmpresaIndexRoute
  '/inversor/': typeof AuthenticatedInversorIndexRoute
  '/proyectos/': typeof AuthenticatedProyectosIndexRoute
  '/empresa/$id/editar': typeof AuthenticatedEmpresaIdEditarRoute
  '/empresa/$id/inversores': typeof AuthenticatedEmpresaIdInversoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/ayuda': typeof AyudaRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/legal': typeof LegalRoute
  '/planes': typeof PlanesRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/app': typeof AuthenticatedAppRoute
  '/conexiones': typeof AuthenticatedConexionesRoute
  '/descubrir': typeof AuthenticatedDescubrirRoute
  '/mensajes': typeof AuthenticatedMensajesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/verificacion': typeof AuthenticatedVerificacionRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/restablecer': typeof AuthRestablecerRoute
  '/proyectos/$id': typeof ProyectosIdRoute
  '/empresa/nuevo': typeof AuthenticatedEmpresaNuevoRoute
  '/empresa/perfil': typeof AuthenticatedEmpresaPerfilRoute
  '/empresa/solicitudes': typeof AuthenticatedEmpresaSolicitudesRoute
  '/inversor/favoritos': typeof AuthenticatedInversorFavoritosRoute
  '/inversor/perfil': typeof AuthenticatedInversorPerfilRoute
  '/inversor/solicitudes': typeof AuthenticatedInversorSolicitudesRoute
  '/empresa': typeof AuthenticatedEmpresaIndexRoute
  '/inversor': typeof AuthenticatedInversorIndexRoute
  '/proyectos': typeof AuthenticatedProyectosIndexRoute
  '/empresa/$id/editar': typeof AuthenticatedEmpresaIdEditarRoute
  '/empresa/$id/inversores': typeof AuthenticatedEmpresaIdInversoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/ayuda': typeof AyudaRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/legal': typeof LegalRoute
  '/planes': typeof PlanesRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/conexiones': typeof AuthenticatedConexionesRoute
  '/_authenticated/descubrir': typeof AuthenticatedDescubrirRoute
  '/_authenticated/mensajes': typeof AuthenticatedMensajesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/verificacion': typeof AuthenticatedVerificacionRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/restablecer': typeof AuthRestablecerRoute
  '/proyectos/$id': typeof ProyectosIdRoute
  '/_authenticated/empresa/nuevo': typeof AuthenticatedEmpresaNuevoRoute
  '/_authenticated/empresa/perfil': typeof AuthenticatedEmpresaPerfilRoute
  '/_authenticated/empresa/solicitudes': typeof AuthenticatedEmpresaSolicitudesRoute
  '/_authenticated/inversor/favoritos': typeof AuthenticatedInversorFavoritosRoute
  '/_authenticated/inversor/perfil': typeof AuthenticatedInversorPerfilRoute
  '/_authenticated/inversor/solicitudes': typeof AuthenticatedInversorSolicitudesRoute
  '/_authenticated/empresa/': typeof AuthenticatedEmpresaIndexRoute
  '/_authenticated/inversor/': typeof AuthenticatedInversorIndexRoute
  '/_authenticated/proyectos/': typeof AuthenticatedProyectosIndexRoute
  '/_authenticated/empresa/$id/editar': typeof AuthenticatedEmpresaIdEditarRoute
  '/_authenticated/empresa/$id/inversores': typeof AuthenticatedEmpresaIdInversoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ayuda'
    | '/contacto'
    | '/cookies'
    | '/legal'
    | '/planes'
    | '/privacidad'
    | '/terminos'
    | '/admin'
    | '/ajustes'
    | '/app'
    | '/conexiones'
    | '/descubrir'
    | '/mensajes'
    | '/onboarding'
    | '/verificacion'
    | '/auth/recuperar'
    | '/auth/restablecer'
    | '/proyectos/$id'
    | '/empresa/nuevo'
    | '/empresa/perfil'
    | '/empresa/solicitudes'
    | '/inversor/favoritos'
    | '/inversor/perfil'
    | '/inversor/solicitudes'
    | '/empresa/'
    | '/inversor/'
    | '/proyectos/'
    | '/empresa/$id/editar'
    | '/empresa/$id/inversores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ayuda'
    | '/contacto'
    | '/cookies'
    | '/legal'
    | '/planes'
    | '/privacidad'
    | '/terminos'
    | '/admin'
    | '/ajustes'
    | '/app'
    | '/conexiones'
    | '/descubrir'
    | '/mensajes'
    | '/onboarding'
    | '/verificacion'
    | '/auth/recuperar'
    | '/auth/restablecer'
    | '/proyectos/$id'
    | '/empresa/nuevo'
    | '/empresa/perfil'
    | '/empresa/solicitudes'
    | '/inversor/favoritos'
    | '/inversor/perfil'
    | '/inversor/solicitudes'
    | '/empresa'
    | '/inversor'
    | '/proyectos'
    | '/empresa/$id/editar'
    | '/empresa/$id/inversores'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/ayuda'
    | '/contacto'
    | '/cookies'
    | '/legal'
    | '/planes'
    | '/privacidad'
    | '/terminos'
    | '/_authenticated/admin'
    | '/_authenticated/ajustes'
    | '/_authenticated/app'
    | '/_authenticated/conexiones'
    | '/_authenticated/descubrir'
    | '/_authenticated/mensajes'
    | '/_authenticated/onboarding'
    | '/_authenticated/verificacion'
    | '/auth/recuperar'
    | '/auth/restablecer'
    | '/proyectos/$id'
    | '/_authenticated/empresa/nuevo'
    | '/_authenticated/empresa/perfil'
    | '/_authenticated/empresa/solicitudes'
    | '/_authenticated/inversor/favoritos'
    | '/_authenticated/inversor/perfil'
    | '/_authenticated/inversor/solicitudes'
    | '/_authenticated/empresa/'
    | '/_authenticated/inversor/'
    | '/_authenticated/proyectos/'
    | '/_authenticated/empresa/$id/editar'
    | '/_authenticated/empresa/$id/inversores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AyudaRoute: typeof AyudaRoute
  ContactoRoute: typeof ContactoRoute
  CookiesRoute: typeof CookiesRoute
  LegalRoute: typeof LegalRoute
  PlanesRoute: typeof PlanesRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosRoute: typeof TerminosRoute
  ProyectosIdRoute: typeof ProyectosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$id': {
      id: '/proyectos/$id'
      path: '/proyectos/$id'
      fullPath: '/proyectos/$id'
      preLoaderRoute: typeof ProyectosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/restablecer': {
      id: '/auth/restablecer'
      path: '/restablecer'
      fullPath: '/auth/restablecer'
      preLoaderRoute: typeof AuthRestablecerRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/recuperar': {
      id: '/auth/recuperar'
      path: '/recuperar'
      fullPath: '/auth/recuperar'
      preLoaderRoute: typeof AuthRecuperarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/verificacion': {
      id: '/_authenticated/verificacion'
      path: '/verificacion'
      fullPath: '/verificacion'
      preLoaderRoute: typeof AuthenticatedVerificacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensajes': {
      id: '/_authenticated/mensajes'
      path: '/mensajes'
      fullPath: '/mensajes'
      preLoaderRoute: typeof AuthenticatedMensajesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/descubrir': {
      id: '/_authenticated/descubrir'
      path: '/descubrir'
      fullPath: '/descubrir'
      preLoaderRoute: typeof AuthenticatedDescubrirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conexiones': {
      id: '/_authenticated/conexiones'
      path: '/conexiones'
      fullPath: '/conexiones'
      preLoaderRoute: typeof AuthenticatedConexionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proyectos/': {
      id: '/_authenticated/proyectos/'
      path: '/proyectos'
      fullPath: '/proyectos/'
      preLoaderRoute: typeof AuthenticatedProyectosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inversor/': {
      id: '/_authenticated/inversor/'
      path: '/inversor'
      fullPath: '/inversor/'
      preLoaderRoute: typeof AuthenticatedInversorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa/': {
      id: '/_authenticated/empresa/'
      path: '/empresa'
      fullPath: '/empresa/'
      preLoaderRoute: typeof AuthenticatedEmpresaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inversor/solicitudes': {
      id: '/_authenticated/inversor/solicitudes'
      path: '/inversor/solicitudes'
      fullPath: '/inversor/solicitudes'
      preLoaderRoute: typeof AuthenticatedInversorSolicitudesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inversor/perfil': {
      id: '/_authenticated/inversor/perfil'
      path: '/inversor/perfil'
      fullPath: '/inversor/perfil'
      preLoaderRoute: typeof AuthenticatedInversorPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inversor/favoritos': {
      id: '/_authenticated/inversor/favoritos'
      path: '/inversor/favoritos'
      fullPath: '/inversor/favoritos'
      preLoaderRoute: typeof AuthenticatedInversorFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa/solicitudes': {
      id: '/_authenticated/empresa/solicitudes'
      path: '/empresa/solicitudes'
      fullPath: '/empresa/solicitudes'
      preLoaderRoute: typeof AuthenticatedEmpresaSolicitudesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa/perfil': {
      id: '/_authenticated/empresa/perfil'
      path: '/empresa/perfil'
      fullPath: '/empresa/perfil'
      preLoaderRoute: typeof AuthenticatedEmpresaPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa/nuevo': {
      id: '/_authenticated/empresa/nuevo'
      path: '/empresa/nuevo'
      fullPath: '/empresa/nuevo'
      preLoaderRoute: typeof AuthenticatedEmpresaNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa/$id/inversores': {
      id: '/_authenticated/empresa/$id/inversores'
      path: '/empresa/$id/inversores'
      fullPath: '/empresa/$id/inversores'
      preLoaderRoute: typeof AuthenticatedEmpresaIdInversoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa/$id/editar': {
      id: '/_authenticated/empresa/$id/editar'
      path: '/empresa/$id/editar'
      fullPath: '/empresa/$id/editar'
      preLoaderRoute: typeof AuthenticatedEmpresaIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedConexionesRoute: typeof AuthenticatedConexionesRoute
  AuthenticatedDescubrirRoute: typeof AuthenticatedDescubrirRoute
  AuthenticatedMensajesRoute: typeof AuthenticatedMensajesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedVerificacionRoute: typeof AuthenticatedVerificacionRoute
  AuthenticatedEmpresaNuevoRoute: typeof AuthenticatedEmpresaNuevoRoute
  AuthenticatedEmpresaPerfilRoute: typeof AuthenticatedEmpresaPerfilRoute
  AuthenticatedEmpresaSolicitudesRoute: typeof AuthenticatedEmpresaSolicitudesRoute
  AuthenticatedInversorFavoritosRoute: typeof AuthenticatedInversorFavoritosRoute
  AuthenticatedInversorPerfilRoute: typeof AuthenticatedInversorPerfilRoute
  AuthenticatedInversorSolicitudesRoute: typeof AuthenticatedInversorSolicitudesRoute
  AuthenticatedEmpresaIndexRoute: typeof AuthenticatedEmpresaIndexRoute
  AuthenticatedInversorIndexRoute: typeof AuthenticatedInversorIndexRoute
  AuthenticatedProyectosIndexRoute: typeof AuthenticatedProyectosIndexRoute
  AuthenticatedEmpresaIdEditarRoute: typeof AuthenticatedEmpresaIdEditarRoute
  AuthenticatedEmpresaIdInversoresRoute: typeof AuthenticatedEmpresaIdInversoresRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedConexionesRoute: AuthenticatedConexionesRoute,
  AuthenticatedDescubrirRoute: AuthenticatedDescubrirRoute,
  AuthenticatedMensajesRoute: AuthenticatedMensajesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedVerificacionRoute: AuthenticatedVerificacionRoute,
  AuthenticatedEmpresaNuevoRoute: AuthenticatedEmpresaNuevoRoute,
  AuthenticatedEmpresaPerfilRoute: AuthenticatedEmpresaPerfilRoute,
  AuthenticatedEmpresaSolicitudesRoute: AuthenticatedEmpresaSolicitudesRoute,
  AuthenticatedInversorFavoritosRoute: AuthenticatedInversorFavoritosRoute,
  AuthenticatedInversorPerfilRoute: AuthenticatedInversorPerfilRoute,
  AuthenticatedInversorSolicitudesRoute: AuthenticatedInversorSolicitudesRoute,
  AuthenticatedEmpresaIndexRoute: AuthenticatedEmpresaIndexRoute,
  AuthenticatedInversorIndexRoute: AuthenticatedInversorIndexRoute,
  AuthenticatedProyectosIndexRoute: AuthenticatedProyectosIndexRoute,
  AuthenticatedEmpresaIdEditarRoute: AuthenticatedEmpresaIdEditarRoute,
  AuthenticatedEmpresaIdInversoresRoute: AuthenticatedEmpresaIdInversoresRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthRecuperarRoute: typeof AuthRecuperarRoute
  AuthRestablecerRoute: typeof AuthRestablecerRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRecuperarRoute: AuthRecuperarRoute,
  AuthRestablecerRoute: AuthRestablecerRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AyudaRoute: AyudaRoute,
  ContactoRoute: ContactoRoute,
  CookiesRoute: CookiesRoute,
  LegalRoute: LegalRoute,
  PlanesRoute: PlanesRoute,
  PrivacidadRoute: PrivacidadRoute,
  TerminosRoute: TerminosRoute,
  ProyectosIdRoute: ProyectosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
